"""The seed track list for the RAG corpus, organized by mood.

This is just data. build_corpus.py reads SEED_BY_MOOD, looks each track up
on Spotify, fetches its lyrics from Genius, embeds the lyrics with Voyage,
and stores everything in the tracks table.

The mood label is stored alongside each track so we can inspect the corpus
later, but vector_search matches on lyric meaning, not on this label.

Total: 435 tracks across 12 moods. Some tracks (especially Hebrew songs)
may fail the lyrics fetch and get skipped; that is expected.
"""

SEED_BY_MOOD: dict[str, list[tuple[str, str]]] = {
    "lonely": [
        ("Wichita Lineman", "Glen Campbell"),
        ("Hurt", "Johnny Cash"),
        ("Eleanor Rigby", "The Beatles"),
        ("Yesterday", "The Beatles"),
        ("All By Myself", "Celine Dion"),
        ("Skinny Love", "Bon Iver"),
        ("re: Stacks", "Bon Iver"),
        ("River", "Joni Mitchell"),
        ("A Case of You", "Joni Mitchell"),
        ("With or Without You", "U2"),
        ("One", "U2"),
        ("I Will Follow You into the Dark", "Death Cab for Cutie"),
        ("Liability", "Lorde"),
        ("Marjorie", "Taylor Swift"),
        ("Motion Sickness", "Phoebe Bridgers"),
        ("Funeral", "Phoebe Bridgers"),
        ("The Night We Met", "Lord Huron"),
        ("Hallelujah", "Leonard Cohen"),
        ("Famous Blue Raincoat", "Leonard Cohen"),
        ("Suzanne", "Leonard Cohen"),
        ("I'm So Lonesome I Could Cry", "Hank Williams"),
        ("Atur Mitzchech", "Arik Einstein"),
        ("Black", "Pearl Jam"),
        ("Lonely Day", "System of a Down"),
        ("Self Control", "Frank Ocean"),
        ("Solo", "Frank Ocean"),
        ("Streets of Philadelphia", "Bruce Springsteen"),
        ("Cleopatra", "The Lumineers"),
        ("About Today", "The National"),
        ("Apartment Story", "The National"),
        ("Older", "Sasha Sloan"),
        ("The Sound of Silence", "Simon & Garfunkel"),
        ("Stay", "Rihanna"),
    ],
    "hopeful": [
        ("Here Comes the Sun", "The Beatles"),
        ("Three Little Birds", "Bob Marley"),
        ("Lovely Day", "Bill Withers"),
        ("Walking on Sunshine", "Katrina and the Waves"),
        ("I Can See Clearly Now", "Johnny Nash"),
        ("What a Wonderful World", "Louis Armstrong"),
        ("Beautiful Day", "U2"),
        ("Fix You", "Coldplay"),
        ("Rise Up", "Andra Day"),
        ("Hall of Fame", "The Script"),
        ("Stronger (What Doesn't Kill You)", "Kelly Clarkson"),
        ("Roar", "Katy Perry"),
        ("Brave", "Sara Bareilles"),
        ("This Is Me", "Keala Settle"),
        ("Rainbow", "Kacey Musgraves"),
        ("Ho Hey", "The Lumineers"),
        ("Send Me on My Way", "Rusted Root"),
        ("Best Day of My Life", "American Authors"),
        ("On Top of the World", "Imagine Dragons"),
        ("Better Together", "Jack Johnson"),
        ("Banana Pancakes", "Jack Johnson"),
        ("Lean on Me", "Bill Withers"),
        ("Bashana Haba'ah", "Ilanit"),
        ("Salaam", "Mosh Ben-Ari"),
        ("Bridge Over Troubled Water", "Simon & Garfunkel"),
        ("Don't Worry Be Happy", "Bobby McFerrin"),
        ("Counting Stars", "OneRepublic"),
        ("Pocketful of Sunshine", "Natasha Bedingfield"),
        ("Unwritten", "Natasha Bedingfield"),
        ("The Climb", "Miley Cyrus"),
        ("Yerushalayim Shel Zahav", "Ofra Haza"),
        ("Don't Stop Believin'", "Journey"),
        ("Heroes", "David Bowie"),
        ("Feeling Good", "Nina Simone"),
    ],
    "angry": [
        ("Killing in the Name", "Rage Against the Machine"),
        ("Bulls on Parade", "Rage Against the Machine"),
        ("Sleep Now in the Fire", "Rage Against the Machine"),
        ("Chop Suey!", "System of a Down"),
        ("B.Y.O.B.", "System of a Down"),
        ("Toxicity", "System of a Down"),
        ("Smells Like Teen Spirit", "Nirvana"),
        ("Heart-Shaped Box", "Nirvana"),
        ("Territorial Pissings", "Nirvana"),
        ("Bring Me to Life", "Evanescence"),
        ("Numb", "Linkin Park"),
        ("In the End", "Linkin Park"),
        ("Crawling", "Linkin Park"),
        ("One Step Closer", "Linkin Park"),
        ("Last Resort", "Papa Roach"),
        ("Animal I Have Become", "Three Days Grace"),
        ("Down with the Sickness", "Disturbed"),
        ("Headstrong", "Trapt"),
        ("Bodies", "Drowning Pool"),
        ("Break Stuff", "Limp Bizkit"),
        ("Master of Puppets", "Metallica"),
        ("Enter Sandman", "Metallica"),
        ("One", "Metallica"),
        ("War Pigs", "Black Sabbath"),
        ("Iron Man", "Black Sabbath"),
        ("Walk", "Pantera"),
        ("Cowboys from Hell", "Pantera"),
        ("Sober", "Tool"),
        ("Schism", "Tool"),
        ("Du Hast", "Rammstein"),
        ("Hit 'Em Up", "2Pac"),
        ("Shook Ones, Pt. II", "Mobb Deep"),
        ("The Way I Am", "Eminem"),
    ],
    "defiant": [
        ("Born to Run", "Bruce Springsteen"),
        ("Born in the U.S.A.", "Bruce Springsteen"),
        ("London Calling", "The Clash"),
        ("Should I Stay or Should I Go", "The Clash"),
        ("Rock the Casbah", "The Clash"),
        ("Anarchy in the U.K.", "Sex Pistols"),
        ("God Save the Queen", "Sex Pistols"),
        ("American Idiot", "Green Day"),
        ("Holiday", "Green Day"),
        ("Boulevard of Broken Dreams", "Green Day"),
        ("We Will Rock You", "Queen"),
        ("We Are the Champions", "Queen"),
        ("Bohemian Rhapsody", "Queen"),
        ("Lose Yourself", "Eminem"),
        ("Till I Collapse", "Eminem"),
        ("Not Afraid", "Eminem"),
        ("Eye of the Tiger", "Survivor"),
        ("I Won't Back Down", "Tom Petty"),
        ("The Times They Are a-Changin'", "Bob Dylan"),
        ("Like a Rolling Stone", "Bob Dylan"),
        ("Blowin' in the Wind", "Bob Dylan"),
        ("Talkin' bout a Revolution", "Tracy Chapman"),
        ("Revolution", "The Beatles"),
        ("Get Up, Stand Up", "Bob Marley"),
        ("Redemption Song", "Bob Marley"),
        ("Pamela", "HaDag Nahash"),
        ("Mashiach Lo Ba", "Shalom Hanoch"),
        ("Yesh Bi Ahava", "Shalom Hanoch"),
        ("Survivor", "Destiny's Child"),
        ("Run the World (Girls)", "Beyonce"),
        ("Fight Song", "Rachel Platten"),
        ("Fight the Power", "Public Enemy"),
        ("We Don't Need Another Hero", "Tina Turner"),
        ("My Way", "Frank Sinatra"),
    ],
    "dreamy": [
        ("Strawberry Fields Forever", "The Beatles"),
        ("Across the Universe", "The Beatles"),
        ("Tomorrow Never Knows", "The Beatles"),
        ("Pink + White", "Frank Ocean"),
        ("White Ferrari", "Frank Ocean"),
        ("Nights", "Frank Ocean"),
        ("Ivy", "Frank Ocean"),
        ("Currents", "Tame Impala"),
        ("The Less I Know the Better", "Tame Impala"),
        ("Feels Like We Only Go Backwards", "Tame Impala"),
        ("Let It Happen", "Tame Impala"),
        ("New Person, Same Old Mistakes", "Tame Impala"),
        ("Midnight City", "M83"),
        ("Cosmic Love", "Florence + The Machine"),
        ("Dog Days Are Over", "Florence + The Machine"),
        ("Holocene", "Bon Iver"),
        ("Calgary", "Bon Iver"),
        ("Innerbloom", "RUFUS DU SOL"),
        ("Solar Power", "Lorde"),
        ("Green Light", "Lorde"),
        ("Bloom", "The Paper Kites"),
        ("Cherry Wine", "Hozier"),
        ("From Eden", "Hozier"),
        ("Like Real People Do", "Hozier"),
        ("La Vie en Rose", "Louis Armstrong"),
        ("Dream a Little Dream of Me", "Ella Fitzgerald"),
        ("In Dreams", "Roy Orbison"),
        ("Sweet Dreams (Are Made of This)", "Eurythmics"),
        ("Dreams", "Fleetwood Mac"),
        ("Wish You Were Here", "Pink Floyd"),
        ("Time", "Pink Floyd"),
        ("Comfortably Numb", "Pink Floyd"),
        ("Such Great Heights", "The Postal Service"),
        ("Boi", "Idan Raichel"),
        ("Seven Seas", "Avishai Cohen"),
        ("Aurora", "Avishai Cohen"),
    ],
    "nostalgic": [
        ("American Pie", "Don McLean"),
        ("Bittersweet Symphony", "The Verve"),
        ("Don't Look Back in Anger", "Oasis"),
        ("Wonderwall", "Oasis"),
        ("Champagne Supernova", "Oasis"),
        ("Mrs. Robinson", "Simon & Garfunkel"),
        ("The Boxer", "Simon & Garfunkel"),
        ("Cat's in the Cradle", "Harry Chapin"),
        ("Brown Eyed Girl", "Van Morrison"),
        ("Into the Mystic", "Van Morrison"),
        ("Moondance", "Van Morrison"),
        ("Heart of Gold", "Neil Young"),
        ("Old Man", "Neil Young"),
        ("Harvest Moon", "Neil Young"),
        ("Tiny Dancer", "Elton John"),
        ("Rocket Man", "Elton John"),
        ("Goodbye Yellow Brick Road", "Elton John"),
        ("Take Me Home, Country Roads", "John Denver"),
        ("Annie's Song", "John Denver"),
        ("Memory", "Barbra Streisand"),
        ("The Way We Were", "Barbra Streisand"),
        ("Time After Time", "Cyndi Lauper"),
        ("True Colors", "Cyndi Lauper"),
        ("In My Life", "The Beatles"),
        ("While My Guitar Gently Weeps", "The Beatles"),
        ("Time in a Bottle", "Jim Croce"),
        ("Photograph", "Ed Sheeran"),
        ("Castle on the Hill", "Ed Sheeran"),
        ("Glory Days", "Bruce Springsteen"),
        ("Atlantic City", "Bruce Springsteen"),
        ("Ani V'Ata", "Arik Einstein"),
        ("Halicha L'Keisariya", "Hannah Senesh"),
        ("Wagon Wheel", "Old Crow Medicine Show"),
        ("The Way You Look Tonight", "Tony Bennett"),
    ],
    "euphoric": [
        ("September", "Earth, Wind & Fire"),
        ("Boogie Wonderland", "Earth, Wind & Fire"),
        ("Let's Groove", "Earth, Wind & Fire"),
        ("Stayin' Alive", "Bee Gees"),
        ("Night Fever", "Bee Gees"),
        ("Le Freak", "Chic"),
        ("Good Times", "Chic"),
        ("I Will Survive", "Gloria Gaynor"),
        ("Disco Inferno", "The Trammps"),
        ("Funkytown", "Lipps Inc."),
        ("Uptown Funk", "Mark Ronson"),
        ("Get Lucky", "Daft Punk"),
        ("One More Time", "Daft Punk"),
        ("Around the World", "Daft Punk"),
        ("Harder, Better, Faster, Stronger", "Daft Punk"),
        ("Levels", "Avicii"),
        ("Wake Me Up", "Avicii"),
        ("Titanium", "David Guetta"),
        ("Closer", "The Chainsmokers"),
        ("Dancing Queen", "ABBA"),
        ("Mamma Mia", "ABBA"),
        ("I Wanna Dance with Somebody", "Whitney Houston"),
        ("Single Ladies (Put a Ring on It)", "Beyonce"),
        ("Crazy in Love", "Beyonce"),
        ("Don't Start Now", "Dua Lipa"),
        ("Levitating", "Dua Lipa"),
        ("Mr. Blue Sky", "Electric Light Orchestra"),
        ("Don't Stop Me Now", "Queen"),
        ("Footloose", "Kenny Loggins"),
        ("(I've Had) The Time of My Life", "Bill Medley"),
        ("Hey Ya!", "OutKast"),
        ("Tudo Bom", "Static & Ben El"),
        ("Tel Aviv", "Omer Adam"),
        ("New York, New York", "Frank Sinatra"),
    ],
    "melancholy": [
        ("The Scientist", "Coldplay"),
        ("Yellow", "Coldplay"),
        ("Trouble", "Coldplay"),
        ("Tears in Heaven", "Eric Clapton"),
        ("Nothing Compares 2 U", "Sinead O'Connor"),
        ("Everybody Hurts", "R.E.M."),
        ("Losing My Religion", "R.E.M."),
        ("The One I Love", "R.E.M."),
        ("November Rain", "Guns N' Roses"),
        ("Don't Cry", "Guns N' Roses"),
        ("Patience", "Guns N' Roses"),
        ("Last Kiss", "Pearl Jam"),
        ("Creep", "Radiohead"),
        ("Karma Police", "Radiohead"),
        ("No Surprises", "Radiohead"),
        ("Fake Plastic Trees", "Radiohead"),
        ("High and Dry", "Radiohead"),
        ("I Will Always Love You", "Whitney Houston"),
        ("My Heart Will Go On", "Celine Dion"),
        ("Someone Like You", "Adele"),
        ("Hello", "Adele"),
        ("Rolling in the Deep", "Adele"),
        ("Skyfall", "Adele"),
        ("To Make You Feel My Love", "Adele"),
        ("Purple Rain", "Prince"),
        ("Ain't No Sunshine", "Bill Withers"),
        ("The Drugs Don't Work", "The Verve"),
        ("Mi'maamakim", "Idan Raichel"),
        ("Mishehu Holech Tamid Iti", "Eyal Golan"),
        ("Una Noche Mas", "Yasmin Levy"),
        ("Wicked Game", "Chris Isaak"),
        ("Mad World", "Gary Jules"),
        ("Streets of London", "Ralph McTell"),
        ("Chum", "Earl Sweatshirt"),
        ("Self<3", "Mavi"),
        ("Cry Me a River", "Julie London"),
    ],
    "anxious": [
        ("Idioteque", "Radiohead"),
        ("Paranoid Android", "Radiohead"),
        ("Everything In Its Right Place", "Radiohead"),
        ("Pyramid Song", "Radiohead"),
        ("There There", "Radiohead"),
        ("Climbing Up the Walls", "Radiohead"),
        ("Where Is My Mind?", "Pixies"),
        ("Black Hole Sun", "Soundgarden"),
        ("Spoonman", "Soundgarden"),
        ("Down in a Hole", "Alice in Chains"),
        ("Man in the Box", "Alice in Chains"),
        ("Closer", "Nine Inch Nails"),
        ("Hurt", "Nine Inch Nails"),
        ("The Hand That Feeds", "Nine Inch Nails"),
        ("Head Like a Hole", "Nine Inch Nails"),
        ("Lullaby", "The Cure"),
        ("Pictures of You", "The Cure"),
        ("A Forest", "The Cure"),
        ("Love Will Tear Us Apart", "Joy Division"),
        ("Disorder", "Joy Division"),
        ("She's Lost Control", "Joy Division"),
        ("Blue Monday", "New Order"),
        ("Smalltown Boy", "Bronski Beat"),
        ("Personal Jesus", "Depeche Mode"),
        ("Enjoy the Silence", "Depeche Mode"),
        ("Stripped", "Depeche Mode"),
        ("Stressed Out", "Twenty One Pilots"),
        ("Heathens", "Twenty One Pilots"),
        ("Ride", "Twenty One Pilots"),
        ("Little Talks", "Of Monsters and Men"),
        ("The Pretender", "Foo Fighters"),
        ("My Hero", "Foo Fighters"),
        ("Everlong", "Foo Fighters"),
        ("Stop Worry!", "MIKE"),
        ("Sinnerman", "Nina Simone"),
    ],
    "romantic": [
        ("At Last", "Etta James"),
        ("Wonderful Tonight", "Eric Clapton"),
        ("Can't Help Falling in Love", "Elvis Presley"),
        ("Love Me Tender", "Elvis Presley"),
        ("Unchained Melody", "The Righteous Brothers"),
        ("Stand by Me", "Ben E. King"),
        ("My Girl", "The Temptations"),
        ("Let's Get It On", "Marvin Gaye"),
        ("Sexual Healing", "Marvin Gaye"),
        ("Adore You", "Harry Styles"),
        ("Watermelon Sugar", "Harry Styles"),
        ("As It Was", "Harry Styles"),
        ("Thinking Out Loud", "Ed Sheeran"),
        ("Perfect", "Ed Sheeran"),
        ("Shape of You", "Ed Sheeran"),
        ("All of Me", "John Legend"),
        ("Stay With You", "John Legend"),
        ("Stay with Me", "Sam Smith"),
        ("Lay Me Down", "Sam Smith"),
        ("Just the Way You Are", "Billy Joel"),
        ("She's Always a Woman", "Billy Joel"),
        ("Lovesong", "The Cure"),
        ("Friday I'm in Love", "The Cure"),
        ("XO", "Beyonce"),
        ("Drunk in Love", "Beyonce"),
        ("Take My Breath Away", "Berlin"),
        ("Always Remember Us This Way", "Lady Gaga"),
        ("Shallow", "Lady Gaga"),
        ("Ana Mashuga", "Idan Raichel"),
        ("Crazy", "Patsy Cline"),
        ("(Everything I Do) I Do It for You", "Bryan Adams"),
        ("Endless Love", "Lionel Richie"),
        ("I'll Make Love to You", "Boyz II Men"),
        ("End of the Road", "Boyz II Men"),
        ("The Light", "Common"),
        ("Fall in Love", "Slum Village"),
        ("See You Again", "Tyler, The Creator"),
        ("Fly Me to the Moon", "Frank Sinatra"),
        ("Strangers in the Night", "Frank Sinatra"),
        ("I Put a Spell on You", "Nina Simone"),
    ],
    "calm": [
        ("Norwegian Wood", "The Beatles"),
        ("Blackbird", "The Beatles"),
        ("Mother Nature's Son", "The Beatles"),
        ("Octopus's Garden", "The Beatles"),
        ("Yellow Submarine", "The Beatles"),
        ("Misty", "Sarah Vaughan"),
        ("Come Away with Me", "Norah Jones"),
        ("Don't Know Why", "Norah Jones"),
        ("Sunny", "Bobby Hebb"),
        ("Lullaby of Birdland", "Sarah Vaughan"),
        ("I Left My Heart in San Francisco", "Tony Bennett"),
        ("Big Yellow Taxi", "Joni Mitchell"),
        ("Angel", "Sarah McLachlan"),
        ("Landslide", "Fleetwood Mac"),
        ("Go Your Own Way", "Fleetwood Mac"),
        ("Riptide", "Vance Joy"),
        ("Stolen Dance", "Milky Chance"),
        ("Electric Love", "BORNS"),
        ("Coffee", "beabadoobee"),
        ("Glue Song", "beabadoobee"),
        ("Sweater Weather", "The Neighbourhood"),
        ("Bubbly", "Colbie Caillat"),
        ("Lucky", "Jason Mraz"),
        ("I'm Yours", "Jason Mraz"),
        ("The Lazy Song", "Bruno Mars"),
        ("Toes", "Zac Brown Band"),
        ("Knee Deep", "Zac Brown Band"),
        ("Free Fallin'", "Tom Petty"),
        ("Tennessee Whiskey", "Chris Stapleton"),
        ("Slow Burn", "Kacey Musgraves"),
        ("Body Like a Back Road", "Sam Hunt"),
        ("Both Sides Now", "Joni Mitchell"),
        ("Lay Lady Lay", "Bob Dylan"),
        ("Summertime", "Ella Fitzgerald"),
        ("Almah Sleeping", "Avishai Cohen"),
        ("Smile", "Avishai Cohen"),
    ],
    "restless": [
        ("Highway to Hell", "AC/DC"),
        ("Back in Black", "AC/DC"),
        ("Thunderstruck", "AC/DC"),
        ("T.N.T.", "AC/DC"),
        ("You Shook Me All Night Long", "AC/DC"),
        ("Mr. Brightside", "The Killers"),
        ("Somebody Told Me", "The Killers"),
        ("Seven Nation Army", "The White Stripes"),
        ("Float On", "Modest Mouse"),
        ("Take Me Out", "Franz Ferdinand"),
        ("Time to Pretend", "MGMT"),
        ("Electric Feel", "MGMT"),
        ("Pumped Up Kicks", "Foster the People"),
        ("1979", "The Smashing Pumpkins"),
        ("HUMBLE.", "Kendrick Lamar"),
        ("DNA.", "Kendrick Lamar"),
        ("Alright", "Kendrick Lamar"),
        ("Money Trees", "Kendrick Lamar"),
        ("Sicko Mode", "Travis Scott"),
        ("Goosebumps", "Travis Scott"),
        ("God's Plan", "Drake"),
        ("Hotline Bling", "Drake"),
        ("Empire State of Mind", "Jay-Z"),
        ("99 Problems", "Jay-Z"),
        ("Can I Kick It?", "A Tribe Called Quest"),
        ("C.R.E.A.M.", "Wu-Tang Clan"),
        ("Still D.R.E.", "Dr. Dre"),
        ("Gin and Juice", "Snoop Dogg"),
        ("Old Town Road", "Lil Nas X"),
        ("Mo Bamba", "Sheck Wes"),
        ("Bodak Yellow", "Cardi B"),
        ("Hey Brother", "Avicii"),
        ("Stay", "Zedd"),
        ("Hahackiblutim", "Stav"),
        ("Self Care", "Mac Miller"),
        ("Best Day Ever", "Mac Miller"),
        ("Donald Trump", "Mac Miller"),
        ("Doomsday", "MF DOOM"),
        ("Accordion", "Madvillain"),
        ("Meat Grinder", "Madvillain"),
        ("Rhymes Like Dimes", "MF DOOM"),
        ("So Far to Go", "J Dilla"),
        ("Won't Do", "J Dilla"),
        ("All Caps", "Madvillain"),
        ("One Beer", "MF DOOM"),
        ("Beef Rapp", "MF DOOM"),
        ("Figaro", "Madvillain"),
        ("Curls", "Madvillain"),
        ("Bullyshit", "Quasimoto"),
        ("None Shall Pass", "Aesop Rock"),
    ],
}


def all_tracks() -> list[tuple[str, str, str]]:
    """Flatten to a list of (track_name, artist, mood) triples."""
    out = []
    for mood, tracks in SEED_BY_MOOD.items():
        for name, artist in tracks:
            out.append((name, artist, mood))
    return out


if __name__ == "__main__":
    tracks = all_tracks()
    print(f"Total tracks: {len(tracks)}")
    print(f"Moods: {len(SEED_BY_MOOD)}")
    for mood, items in SEED_BY_MOOD.items():
        print(f"  {mood:12} {len(items)}")
    # Sanity check for accidental duplicates across the whole list.
    seen = set()
    dupes = []
    for name, artist, _ in tracks:
        key = (name.lower(), artist.lower())
        if key in seen:
            dupes.append((name, artist))
        seen.add(key)
    if dupes:
        print(f"\nWARNING: {len(dupes)} duplicate(s):")
        for d in dupes:
            print(f"  {d}")
    else:
        print("\nNo duplicates.")
